### PR TITLE
Allow verify_ssl

### PR DESCRIPTION
**Pull request by ahmet2mir**
If the endpoint is insecure, allow verify_ssl option, --no-verify-ssl on CLI.

### CODE REVIEW

**Comment by ahmet2mir** [comment]
(i could flat the 3 commits if needed)

**Comment by wbingli** [comment]
LGTM, merging.

**Comment by wbingli** [comment]
Thanks, @ahmet2mir

**Comment by wbingli** [comment]
I will publish to pip soon.

**Comment by ahmet2mir** [comment]
YW :)

**Pull request merged**
